export const SHOPPING_MODE = '[SSL] SHOPPPING_MODE';
export const EDIT_MODE = '[SSL] EDIT_LIST_MODE';

export const LIBRARY_KEY = '[SSL] LIBRARY_KEY';
export const ITEM_GROUP_KEY = '[SSL] ITEM_GROUP_KEY';
export const SHOPPING_LIST_KEY = '[SSL] SHOPPING_LIST_KEY';

export const MODAL_ADD_MODE = '[SSL] MODAL_ADD_MODE';
export const MODAL_EDIT_MODE = '[SSL] MODAL_EDIT_MODE';
